name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: PROD

    env:
      SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH into server and deploy application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} -p 24700 << EOF
          source /root/.bashrc

          cd /root/portfolio

          # Set GitHub credentials using GITHUB_TOKEN
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" > ~/.git-credentials

          # Pull the latest code from the repository
          git pull origin master

          # Check npm command is available, if not install it
          if ! command -v npm &> /dev/null
          then
              curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
              sudo apt-get install -y nodejs
          fi

          # Install dependencies
          npm i

          # Check pm2 command is available, if not install it
          if ! command -v pm2 &> /dev/null
          then
              npm install pm2 -g
          fi

          # Build
          npm run build

          # Restart the service
          pm2 reload ecosytem.config.js
        EOF
